### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by Arijit-017** [Arijit-017/ISTE-Contribution-React#18]
# Issue: Add Footer and Subfooter to Contributors Display Project

## Description

I would like to add a footer to the Contributors Display Project. The footer should have a black background and include a subfooter for copyright information.

### Requirements

1. **Footer**:
   - Background color: Black
   - Content: Relevant links or information about the project (to be determined).

2. **Subfooter**:
   - Content: Copyright notice
     ```
     You can directly copy and paste this Markdown into your `README.md` file. Let me know if you need further edits!
     ```

### Additional Information

For more context about the project and its association, you can refer to the **Indian Society for Technical Education (ISTE)** page [here](https://hitiste.vercel.app/).

### Tasks

- [ ] Implement the footer with the specified background color.
- [ ] Add the subfooter with the copyright notice.
- [ ] Ensure responsive design for different screen sizes.

Please feel free to comment or ask any questions regarding this issue!

**Comment by Jagannathroy** [comment]
Hey @Arijit-017 , I can fix this issue by adding a footer and subfooter as required.

/assign

**Comment by Jagannathroy** [comment]
Hey @Arijit-017 , I can fix this issue by adding header and subheader as required. Please assign this issue to me.

**Comment by misanthropic-codes** [comment]
i can fix this please assign this to me

**Comment by Arijit-017** [comment]
> i can fix this please assign this to me

@misanthropic-codes issue resolved you can improve the design

**Comment by misanthropic-codes** [comment]
> > i can fix this please assign this to me
> 
> @misanthropic-codes issue resolved you can improve the design

okay sure
